include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # ✅ 强烈建议写类型，便于可读性和调试
    always_specify_types: true

    # ✅ 局部变量如果不需要改动，用 final 提升安全性
    prefer_final_locals: true
    prefer_final_in_for_each: true

    # ✅ 用 const 优化性能（尤其 Flutter UI）
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true

    # ✅ 排序 import 语句
    directives_ordering: true

    # ✅ 避免空判断错误
    unnecessary_null_checks: true

    # ✅ 提升可读性
    avoid_positional_boolean_parameters: true
    prefer_expression_function_bodies: true

    # ✅ 避免没用的代码
    unnecessary_lambdas: true
    avoid_print: true
    avoid_empty_else: true

    # ✅ 有些细节上的语义提升
    join_return_with_assignment: true
    use_named_constants: true
    no_logic_in_create_state: true
    avoid_classes_with_only_static_members: true

analyzer:
  exclude:
    - "**.g.dart"
    - "**.freezed.dart"
    - "**.gr.dart"
    - "**.config.dart"